# Ethnicity

## Setup

In [35]:
from matplotlib.colors import ListedColormap 
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter, AutoMinorLocator)
from lib import formatting as sd_formatting
import pyodbc 
import toml
import config_logging
import logging
import urllib.request
import pandas as pd
import colorcet as cc

log = logging.getLogger(__name__)
external_ip = urllib.request.urlopen('https://ident.me').read().decode('utf8')

properties = toml.load("./.streamlit/secrets.toml")

database_props = properties[properties["database"]["flavour"]]

## Reload

In [36]:
### Set up
%load_ext autoreload

%autoreload 3
from data.daos import dao_facade_local as dao_fac
from lib import db_tools as db_tools
from lib import masters_data_analytics_lib as mlib
from lib import stats as stats

db_conn = None
db_conn = db_tools.get_db_conn(database_props)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
2022-08-28 15:20:03,577 [INFO] lib.db_tools: DATABASE CONNECTIVITY

## Build the Data

### Search Critera & DAO Access to get all required data

In [37]:
city      = "London"

borough   = "Islington"
ward_name = "Holloway"

## 27% Black African Carribean at Borough Level
borough   = "Lewisham"
ward_name = "Bellingham"

borough   = "Merton"
ward_name = "Dundonald"

year_from = 2009
year_to   = 2022

# borough   = "Westminster"    # Highest
# borough   = "Brent"          # Middle
# borough   = "City of London" # Lowest

## We may not have data in the date range we have chosen
## this is true for ALL so fix it Neal

ethnicity_year_from = year_from
ethnicity_year_to   = year_to

# What do we have? We are only using the max for now
ethnicity_min_max_year_df = dao_fac.ethnicity_min_max_year(db_conn)

ethnicity_year_min = ethnicity_min_max_year_df["MIN_YEAR"].values[0]
ethnicity_year_max = ethnicity_min_max_year_df["MAX_YEAR"].values[0]

ethnicity_year_from_orig = ethnicity_year_from
ethnicity_year_to_orig = ethnicity_year_to

if ethnicity_year_from < int(ethnicity_year_min):
    ethnicity_year_from = int(ethnicity_year_min)
elif ethnicity_year_from > int(ethnicity_year_max):
    ethnicity_year_from = int(ethnicity_year_max)

if ethnicity_year_to > int(ethnicity_year_max):
    ethnicity_year_to = int(ethnicity_year_max)
elif ethnicity_year_to < int(ethnicity_year_min):
    ethnicity_year_to = int(ethnicity_year_min)

log.debug(f"ethnicity orig_year_to    :{ethnicity_year_to_orig}")
log.debug(f"ethnicity search_year_to  :{ethnicity_year_to}")

search_term = {"year_from":ethnicity_year_from,
               "year_to":ethnicity_year_to,
               "borough":borough,
               "ward_name":ward_name}

## City
ethnicity_average_year_df = dao_fac.ethnicity_ratio_average_years(db_conn, search_term)
## Borough
ethnicity_by_borough_year_df = dao_fac.ethnicity_ratio_by_borough_years(db_conn, search_term)
## Ward
ethnicity_by_borough_ward_year_df = dao_fac.ethnicity_ratio_by_borough_ward_years(db_conn, search_term)

2022-08-28 15:20:03,714 [DEBUG] __main__: ethnicity orig_year_to    :2021
2022-08-28 15:20:03,716 [DEBUG] __main__: ethnicity search_year_to  :2011

In [38]:
## Ethnicity Search Range Narrative
ethnicity_narrative_01 = ""
ethnicity_in_not_in = "in" if ((ethnicity_year_to >= ethnicity_year_from_orig) &
                               (ethnicity_year_to <= ethnicity_year_to)) else "outside"

ethnicity_search_range = f"of {ethnicity_year_from_orig} to {ethnicity_year_to_orig}" if ethnicity_year_from_orig != ethnicity_year_to_orig else f"{ethnicity_year_to_orig}"
ethnicity_narrative_search_criters = f"Using the latest ethnicity data from {ethnicity_year_to} which is {ethnicity_in_not_in} your search range {ethnicity_search_range}"

ethnicity_narrative_01 = f"{ethnicity_narrative_search_criters}. The table below ranks ethnicity in {ward_name}, {borough} and {city}. " + \
"The ranking is highest to lowest percentage from top to bottom. Where there is a difference in ethnicity the cell is shaded, a darker " + \
"shade denotes a difference between borough and ward. Values in [] give the percentage value." 

log.debug(f"\n{ethnicity_narrative_01}")

2022-08-28 15:20:03,852 [DEBUG] __main__:
Using the latest ethnicity data from 2011 which is in your search range of 2011 to 2021. The table below ranks ethnicity in Dundonald, Merton and London. The ranking is highest to lowest percentage from top to bottom. Where there is a difference in ethnicity the cell is shaded, a darker shade denotes a difference between borough and ward. Values in [] give the percentage value.

#### Build the data and ranking table for ward, borough and city

In [39]:
## Borough & Ward
ethnicity_borough_ward_for_year = ethnicity_by_borough_ward_year_df.copy()
ethnicity_borough_ward_for_year = ethnicity_borough_ward_for_year.drop(["YEAR", "LAD", "LAD_NAME", "WARD_CODE", "WARD_NAME"], axis=1)
ethnicity_borough_ward_for_year = ethnicity_borough_ward_for_year.T.copy()
ethnicity_borough_ward_for_year.columns = ["PCT"]
ethnicity_borough_ward_for_year = ethnicity_borough_ward_for_year.sort_values(by=["PCT"], ascending=False)

## Borough
ethnicity_borough_for_year = ethnicity_by_borough_year_df[ethnicity_by_borough_year_df["LAD_NAME"] == borough].copy()
ethnicity_borough_for_year = ethnicity_borough_for_year.drop(["YEAR", "LAD", "LAD_NAME"], axis=1)
ethnicity_borough_for_year = ethnicity_borough_for_year.T.copy()
ethnicity_borough_for_year.columns = ["PCT"]
ethnicity_borough_for_year = ethnicity_borough_for_year.sort_values(by=["PCT"], ascending=False)

## City
ethnicity_city_for_year = ethnicity_average_year_df.copy()
ethnicity_city_for_year
ethnicity_city_for_year = ethnicity_city_for_year.drop(["YEAR"], axis=1)
ethnicity_city_for_year = ethnicity_city_for_year.T.copy()
ethnicity_city_for_year.columns = ["PCT"]
ethnicity_city_for_year = ethnicity_city_for_year.sort_values(by=["PCT"], ascending=False)

## Borough Ward
ethnicity_ward_pct_sorted = []
for index, row in ethnicity_borough_ward_for_year.iterrows():
    ethnicity     = index
    ethncity_pct = row.values[0]*100
    ethnicity_name_pct_fmt = "{} - [{:,.2f}%]".format(ethnicity, ethncity_pct)
    ethnicity_ward_pct_sorted.append(ethnicity_name_pct_fmt)

## Borough
ethnicity_borough_pct_sorted = []
for index, row in ethnicity_borough_for_year.iterrows():
    ethnicity     = index
    ethncity_pct = row.values[0]*100
    ethnicity_name_pct_fmt = "{} - [{:,.2f}%]".format(ethnicity, ethncity_pct)
    ethnicity_borough_pct_sorted.append(ethnicity_name_pct_fmt)

## City
ethnicity_city_pct_sorted = []
for index, row in     ethnicity_city_for_year.iterrows():
    ethnicity     = index
    ethncity_pct = row.values[0]*100
    ethnicity_name_pct_fmt = "{} - [{:,.2f}%]".format(ethnicity, ethncity_pct)
    ethnicity_city_pct_sorted.append(ethnicity_name_pct_fmt)

ethnicity_ward_borough_city_pct_ranked_merged = [ethnicity_ward_pct_sorted, ethnicity_borough_pct_sorted, ethnicity_city_pct_sorted]
ethnicity_ward_borough_city_pct_ranked_merged_df = pd.DataFrame(data=ethnicity_ward_borough_city_pct_ranked_merged)

## Rotate 
ethnicity_ward_borough_city_pct_ranked_merged_df = ethnicity_ward_borough_city_pct_ranked_merged_df.T
ethnicity_ward_borough_city_pct_ranked_merged_df.columns = [f"{ward_name}",f"{borough}",f"{city}"]
ethnicity_ward_borough_city_pct_ranked_merged_df.index   = [str(rank) for rank in range(1, len(ethnicity_ward_borough_city_pct_ranked_merged_df.index)+1)]

ethnicity_ward_borough_city_pct_ranked_merged_df

,Dundonald,Merton,London
1,White - [81.89%],White - [64.79%],White - [61.61%]
2,Mixed Ethnic - [4.80%],Black African Caribbean - [10.42%],Black African Caribbean - [12.24%]
3,British Asian Other - [3.82%],British Asian Other - [7.95%],British Indian - [6.31%]
4,British Indian - [3.59%],Mixed Ethnic - [4.67%],Mixed Ethnic - [4.88%]
5,Black African Caribbean - [1.52%],British Indian - [4.06%],British Asian Other - [4.75%]
6,Other - [1.40%],British Pakistani - [3.67%],Other - [3.39%]
7,British Chinese - [1.27%],Other - [1.90%],British Bangladeshi - [2.55%]
8,British Pakistani - [1.22%],British Chinese - [1.31%],British Pakistani - [2.50%]
9,British Bangladeshi - [0.47%],British Bangladeshi - [1.11%],British Chinese - [1.67%]
10,Gypsy Irish Traveller - [0.02%],Gypsy Irish Traveller - [0.11%],Gypsy Irish Traveller - [0.10%]

## Build the Ethnicity table with formatting

In [40]:
colour_change = []
## 0 == no change in that cell
## 1 == shade 1 change
## 2 == shade 2 change

for index, row in ethnicity_ward_borough_city_pct_ranked_merged_df.iterrows():
    colour_change_row =[]
    
    ## Borough to City Check
    ward_val    = row.iloc[0].split(' - [')[0].strip()
    borough_val = row.iloc[1].split(' - [')[0].strip()
    city_val    = row.iloc[2].split(' - [')[0].strip()
    # log.debug(f"{ward_val}-{borough_val}-{city_val}")

    ward_val_cell_col = 0 if ward_val     == city_val else 1 if ward_val == borough_val else 2
    borough_val_col   = 0 if borough_val  == city_val else 1
    cityl_col         = 0
    
    colour_change_row.append(ward_val_cell_col)
    colour_change_row.append(borough_val_col)
    colour_change_row.append(cityl_col)
    colour_change.append(colour_change_row)

def format_ranking_row(row):
    ## Borough to City Check
    ward_val    = row.iloc[0].split(' - [')[0].strip()
    borough_val = row.iloc[1].split(' - [')[0].strip()
    city_val    = row.iloc[2].split(' - [')[0].strip()
    # log.debug(f"{ward_val}-{borough_val}-{city_val}")

    ward_val_cell_col = "" if ward_val     == city_val else "background-color: #EAFAF1" if ward_val == borough_val else "background-color: #D5F5E3"
    borough_val_col   = "" if borough_val  == city_val else "background-color: #EAFAF1"
    # log.debug(r[1])
    return [ward_val_cell_col] + [borough_val_col] + [""]


from IPython.display import HTML
styles = [
  dict(selector="tr", props=[("font-size", "110%"),
                             ("text-align", "right")])
]

ethnicity_ward_borough_city_pct_ranked_merged_df_html = (ethnicity_ward_borough_city_pct_ranked_merged_df.style.set_table_styles(styles).apply(format_ranking_row, axis=1))

In [41]:
ethnicity_ward_borough_city_pct_ranked_merged_df_html

In [42]:
ethnicity_borough_ward_for_year_name_sorted = ethnicity_borough_ward_for_year.sort_index(ascending=True)
ethnicity_borough_for_year_name_sorted      = ethnicity_borough_for_year.sort_index(ascending=True)
ethnciity_city_for_year_name_sorted         = ethnicity_city_for_year.sort_index(ascending=True)


## Borough Ward
ethnicity_ward_name_sorted = []
for index, row in ethnicity_borough_ward_for_year_name_sorted.iterrows():
    ethnciity_pct = row.values[0]*100
    ethnicity_pct_fmt = "{:,.2f}%".format(ethnciity_pct)
    ethnicity_ward_name_sorted.append(ethnicity_pct_fmt)

## Borough
ethnicity_borough_name_sorted = []
for index, row in ethnicity_borough_for_year_name_sorted.iterrows():
    ethnciity_pct = row.values[0]*100
    ethnicity_pct_fmt = "{:,.2f}%".format(ethnciity_pct)
    ethnicity_borough_name_sorted.append(ethnicity_pct_fmt)

## City
ethnicity_city_name_sorted = []
for index, row in ethnciity_city_for_year_name_sorted.iterrows():
    ethnicity_pct = row.values[0]*100
    ethnicity_pct_fmt = "{:,.2f}%".format(ethnicity_pct)
    ethnicity_city_name_sorted.append(ethnicity_pct_fmt)

ethnicity_ward_borough_city_pct_name_merged = [ethnicity_ward_name_sorted, ethnicity_borough_name_sorted, ethnicity_city_name_sorted]
ethnicity_ward_borough_city_pct_name_merged_df = pd.DataFrame(data=ethnicity_ward_borough_city_pct_name_merged)

## Rotate 
ethnicity_ward_borough_city_pct_name_merged_df = ethnicity_ward_borough_city_pct_name_merged_df.T
ethnicity_ward_borough_city_pct_name_merged_df.columns = [f"{ward_name}",f"{borough}",f"{city}"]
ethnicity_ward_borough_city_pct_name_merged_df.index   = ethnicity_borough_ward_for_year_name_sorted.index

ethnicity_ward_borough_city_pct_name_merged_df

                        Dundonald  Merton  London
Black African Caribbean     1.52%  10.42%  12.24%
British Asian Other         3.82%   7.95%   4.75%
British Bangladeshi         0.47%   1.11%   2.55%
British Chinese             1.27%   1.31%   1.67%
British Indian              3.59%   4.06%   6.31%
British Pakistani           1.22%   3.67%   2.50%
Gypsy Irish Traveller       0.02%   0.11%   0.10%
Mixed Ethnic                4.80%   4.67%   4.88%
Other                       1.40%   1.90%   3.39%
White                      81.89%  64.79%  61.61%

In [43]:
def format_pct_row(row):
    ## Borough to City Check
    ward_val    = float(row.iloc[0].split("%")[0].strip())
    borough_val = float(row.iloc[1].split("%")[0].strip())
    city_val    = float(row.iloc[2].split("%")[0].strip())
    
    ward_val_cell_col = ""                          if abs(city_val - ward_val) <  5.0 else \
                        "background-color: #EAFAF1" if abs(city_val - ward_val) < 10.0 else \
                        "background-color: #D5F5E3" if abs(city_val - ward_val) < 15.0 else \
                        "background-color: #ABEBC6" if abs(city_val - ward_val) < 20.0 else \
                        "background-color: #82E0AA"
    
    borough_val_col   = ""                          if abs(city_val - borough_val) <  5.0 else \
                        "background-color: #EAFAF1" if abs(city_val - borough_val) < 10.0 else \
                        "background-color: #D5F5E3" if abs(city_val - borough_val) < 15.0 else \
                        "background-color: #ABEBC6" if abs(city_val - borough_val) < 20.0 else \
                        "background-color: #82E0AA"
    
    return [ward_val_cell_col] + [borough_val_col] + [""]


from IPython.display import HTML
styles = [
  dict(selector="tr", props=[("font-size", "110%"),
                             ("text-align", "right")])
]

ethnicity_ward_borough_city_pct_name_merged_df_html = (ethnicity_ward_borough_city_pct_name_merged_df.style.set_table_styles(styles).apply(format_pct_row, axis=1))

In [44]:
ethnicity_narrative_02 = f"The table below shows the percentage levels of ethnicity in {ward_name}, {borough} and {city} in {ethnicity_year_to}." + \
" The order of ethnicity is alphabetical. Value shading indicates a difference from the city level from 5 to 20 percent in 5 percent intervals." + \
" The shade darkens with an increase in difference. Indication of the direction of the difference is intentionally not made."

log.debug(f"\n{ethnicity_narrative_02}")

2022-08-28 15:20:04,679 [DEBUG] __main__:
The table below shows the percentage levels of ethnicity in Dundonald, Merton and London in 2011. The order of ethnicity is alphabetical. Value shading indicates a difference from the city level from 5 to 20 percent in 5 percent intervals. The shade darkens with an increase in difference. Indication of the direction of the difference is intentionally not made.

In [45]:
ethnicity_ward_borough_city_pct_name_merged_df_html

# REPORT PAGE

In [46]:
print(ethnicity_narrative_01)

Using the latest ethnicity data from 2011 which is in your search range of 2011 to 2021. The table below ranks ethnicity in Dundonald, Merton and London. The ranking is highest to lowest percentage from top to bottom. Where there is a difference in ethnicity the cell is shaded, a darker shade denotes a difference between borough and ward. Values in [] give the percentage value.

In [47]:
ethnicity_ward_borough_city_pct_ranked_merged_df_html

In [48]:
print(ethnicity_narrative_02)

The table below shows the percentage levels of ethnicity in Dundonald, Merton and London in 2011. The order of ethnicity is alphabetical. Value shading indicates a difference from the city level from 5 to 20 percent in 5 percent intervals. The shade darkens with an increase in difference. Indication of the direction of the difference is intentionally not made.

In [49]:
ethnicity_ward_borough_city_pct_name_merged_df_html

# REPORT GENERATION

## ARTEFACTS

In [50]:
### Set up
%load_ext autoreload

%autoreload 3
from data.daos import dao_facade_local as dao_fac
from lib import masters_data_analytics_lib as mlib
from managers.sections import sd_report_section_03_Ethnicity as report_section_ethnicity

session_id = "SECTION_TEST_03_ETHNICITY"
report_context = {}
search_term = {
    "city"      : city
  , "borough"   : borough
  , "ward_name" : ward_name
  , "year_to"   : year_to
  , "year_from" : year_from
}

report_section_ethnicity.generate_report_section(session_id     = session_id
                      , search_term    = search_term
                      , report_context = report_context
                      , properties     = properties 
                      , dao_fac        = dao_fac)  

# log.debug(report_context)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
2022-08-28 15:20:06,309 [INFO] lib.db_tools: DATABASE CONNECTIVITY
2022-08-28 15:20:06,311 [DEBUG] root: Retrieving ethnicity min max year
2022-08-28 15:20:06,359 [DEBUG] root: ethnicity_ratio_average_years

C:\DISTRIBUTIONS\Python\Python3_10_2\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(
C:\DISTRIBUTIONS\Python\Python3_10_2\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

2022-08-28 15:20:07,831 [DEBUG] root: ethnicity_ratio_by_borough_years

C:\DISTRIBUTIONS\Python\Python3_10_2\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

2022-08-28 15:20:08,803 [DEBUG] root: ethnicity_ratio_by_borough_ward_years

C:\DISTRIBUTIONS\Python\Python3_10_2\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

## REPORT

In [51]:
%load_ext autoreload

%autoreload 3

from managers import sd_report_manager_new as report_man

report_context_new = {"template_processor_file_name":"./reports/processors/sd_test_generation_03_ethnicity.json",
                      "report_option":1} 

report_context.update(report_context_new)

log.debug("Started")
generated_report = report_man.generate_report(session_id
                                            , report_context = report_context
                                            , properties = properties)
log.debug("Finished")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
2022-08-28 15:20:09,216 [DEBUG] __main__: Started
2022-08-28 15:20:09,238 [DEBUG] managers.sd_report_manager_new: text_alignment:justify
2022-08-28 15:20:09,256 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,257 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,258 [DEBUG] managers.sd_report_manager_new: {'ethnicity_narrative_01': 'Using the latest ethnicity data from 2011 which is in your search range of 2011 to 2021. The table {} ranks ethnicity in Dundonald, Merton and London. The ranking is highest to lowest percentage from top to bottom. Where there is a difference in ethnicity the cell is shaded, a darker shade denotes a difference between borough and ward. Values in [] give the percentage value.', 'ethnicity_pct_ranking_table':                             Dundonald                              Merton  \
1                    White - [81.89%]                    White - [64.79%]
2              Mixed Ethnic - [4.80%]  Black African Caribbean - [10.42%]
3       British Asian Other - [3.82%]       British Asian Other - [7.95%]
4            British Indian - [3.59%]              Mixed Ethnic - [4.67%]
5   Black African Caribbean - [1.52%]            British Indian - [4.06%]
6                     Other - [1.40%]         British Pakistani - [3.67%]
7           British Chinese - [1.27%]                     Other - [1.90%]
8         British Pakistani - [1.22%]           British Chinese - [1.31%]
9       British Bangladeshi - [0.47%]       British Bangladeshi - [1.11%]
10    Gypsy Irish Traveller - [0.02%]     Gypsy Irish Traveller - [0.11%]

                                London
1                     White - [61.61%]
2   Black African Caribbean - [12.24%]
3             British Indian - [6.31%]
4               Mixed Ethnic - [4.88%]
5        British Asian Other - [4.75%]
6                      Other - [3.39%]
7        British Bangladeshi - [2.55%]
8          British Pakistani - [2.50%]
9            British Chinese - [1.67%]
10     Gypsy Irish Traveller - [0.10%]  , 'ethnicity_pct_ranking_table_shading': [['', '', ''], ['#D5F5E3', '', ''], ['#EAFAF1', '#EAFAF1', ''], ['#D5F5E3', '', ''], ['#D5F5E3', '#EAFAF1', ''], ['', '#EAFAF1', ''], ['#D5F5E3', '#EAFAF1', ''], ['', '#EAFAF1', ''], ['#EAFAF1', '#EAFAF1', ''], ['', '', '']], 'ethnicity_pct_comparison_table':                                        Ethnicity Dundonald  Merton  London
Black African Caribbean  Black African Caribbean     1.52%  10.42%  12.24%
British Asian Other          British Asian Other     3.82%   7.95%   4.75%
British Bangladeshi          British Bangladeshi     0.47%   1.11%   2.55%
British Chinese                  British Chinese     1.27%   1.31%   1.67%
British Indian                    British Indian     3.59%   4.06%   6.31%
British Pakistani              British Pakistani     1.22%   3.67%   2.50%
Gypsy Irish Traveller      Gypsy Irish Traveller     0.02%   0.11%   0.10%
Mixed Ethnic                        Mixed Ethnic     4.80%   4.67%   4.88%
Other                                      Other     1.40%   1.90%   3.39%
White                                      White    81.89%  64.79%  61.61%, 'ethnicity_pct_comparison_table_shading': [['', '#D5F5E3', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '#82E0AA', '', '#EAFAF1']], 'ethnicity_narrative_02': 'The table {} shows the percentage levels of ethnicity in Dundonald, Merton and London in 2011. The order of ethnicity is alphabetical. Value shading indicates a difference from the city level from 5 to 20 percent in 5 percent intervals. The shade darkens with an increase in difference. Indication of the direction of the difference is intentionally not made.', 'template_processor_file_name': './reports/processors/sd_test_generation_03_ethnicity.json', 'report_option': 1}
2022-08-28 15:20:09,269 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,271 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,375 [WARNING] managers.sd_report_manager_new: Not a Command
2022-08-28 15:20:09,376 [WARNING] managers.sd_report_manager_new: Not a Command
2022-08-28 15:20:09,390 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,391 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,392 [DEBUG] managers.sd_report_manager_new: {'ethnicity_narrative_01': 'Using the latest ethnicity data from 2011 which is in your search range of 2011 to 2021. The table {} ranks ethnicity in Dundonald, Merton and London. The ranking is highest to lowest percentage from top to bottom. Where there is a difference in ethnicity the cell is shaded, a darker shade denotes a difference between borough and ward. Values in [] give the percentage value.', 'ethnicity_pct_ranking_table':                             Dundonald                              Merton  \
1                    White - [81.89%]                    White - [64.79%]
2              Mixed Ethnic - [4.80%]  Black African Caribbean - [10.42%]
3       British Asian Other - [3.82%]       British Asian Other - [7.95%]
4            British Indian - [3.59%]              Mixed Ethnic - [4.67%]
5   Black African Caribbean - [1.52%]            British Indian - [4.06%]
6                     Other - [1.40%]         British Pakistani - [3.67%]
7           British Chinese - [1.27%]                     Other - [1.90%]
8         British Pakistani - [1.22%]           British Chinese - [1.31%]
9       British Bangladeshi - [0.47%]       British Bangladeshi - [1.11%]
10    Gypsy Irish Traveller - [0.02%]     Gypsy Irish Traveller - [0.11%]

                                London
1                     White - [61.61%]
2   Black African Caribbean - [12.24%]
3             British Indian - [6.31%]
4               Mixed Ethnic - [4.88%]
5        British Asian Other - [4.75%]
6                      Other - [3.39%]
7        British Bangladeshi - [2.55%]
8          British Pakistani - [2.50%]
9            British Chinese - [1.67%]
10     Gypsy Irish Traveller - [0.10%]  , 'ethnicity_pct_ranking_table_shading': [['', '', ''], ['#D5F5E3', '', ''], ['#EAFAF1', '#EAFAF1', ''], ['#D5F5E3', '', ''], ['#D5F5E3', '#EAFAF1', ''], ['', '#EAFAF1', ''], ['#D5F5E3', '#EAFAF1', ''], ['', '#EAFAF1', ''], ['#EAFAF1', '#EAFAF1', ''], ['', '', '']], 'ethnicity_pct_comparison_table':                                        Ethnicity Dundonald  Merton  London
Black African Caribbean  Black African Caribbean     1.52%  10.42%  12.24%
British Asian Other          British Asian Other     3.82%   7.95%   4.75%
British Bangladeshi          British Bangladeshi     0.47%   1.11%   2.55%
British Chinese                  British Chinese     1.27%   1.31%   1.67%
British Indian                    British Indian     3.59%   4.06%   6.31%
British Pakistani              British Pakistani     1.22%   3.67%   2.50%
Gypsy Irish Traveller      Gypsy Irish Traveller     0.02%   0.11%   0.10%
Mixed Ethnic                        Mixed Ethnic     4.80%   4.67%   4.88%
Other                                      Other     1.40%   1.90%   3.39%
White                                      White    81.89%  64.79%  61.61%, 'ethnicity_pct_comparison_table_shading': [['', '#D5F5E3', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '#82E0AA', '', '#EAFAF1']], 'ethnicity_narrative_02': 'The table {} shows the percentage levels of ethnicity in Dundonald, Merton and London in 2011. The order of ethnicity is alphabetical. Value shading indicates a difference from the city level from 5 to 20 percent in 5 percent intervals. The shade darkens with an increase in difference. Indication of the direction of the difference is intentionally not made.', 'template_processor_file_name': './reports/processors/sd_test_generation_03_ethnicity.json', 'report_option': 1}
2022-08-28 15:20:09,404 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,405 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,438 [DEBUG] managers.sd_report_manager_new: text_alignment:justify
2022-08-28 15:20:09,439 [WARNING] managers.sd_report_manager_new: Not a Command
2022-08-28 15:20:09,544 [WARNING] managers.sd_report_manager_new: Not a Command
2022-08-28 15:20:09,545 [WARNING] managers.sd_report_manager_new: Not a Command
2022-08-28 15:20:09,556 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,557 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,557 [DEBUG] managers.sd_report_manager_new: {'ethnicity_narrative_01': 'Using the latest ethnicity data from 2011 which is in your search range of 2011 to 2021. The table {} ranks ethnicity in Dundonald, Merton and London. The ranking is highest to lowest percentage from top to bottom. Where there is a difference in ethnicity the cell is shaded, a darker shade denotes a difference between borough and ward. Values in [] give the percentage value.', 'ethnicity_pct_ranking_table':                             Dundonald                              Merton  \
1                    White - [81.89%]                    White - [64.79%]
2              Mixed Ethnic - [4.80%]  Black African Caribbean - [10.42%]
3       British Asian Other - [3.82%]       British Asian Other - [7.95%]
4            British Indian - [3.59%]              Mixed Ethnic - [4.67%]
5   Black African Caribbean - [1.52%]            British Indian - [4.06%]
6                     Other - [1.40%]         British Pakistani - [3.67%]
7           British Chinese - [1.27%]                     Other - [1.90%]
8         British Pakistani - [1.22%]           British Chinese - [1.31%]
9       British Bangladeshi - [0.47%]       British Bangladeshi - [1.11%]
10    Gypsy Irish Traveller - [0.02%]     Gypsy Irish Traveller - [0.11%]

                                London
1                     White - [61.61%]
2   Black African Caribbean - [12.24%]
3             British Indian - [6.31%]
4               Mixed Ethnic - [4.88%]
5        British Asian Other - [4.75%]
6                      Other - [3.39%]
7        British Bangladeshi - [2.55%]
8          British Pakistani - [2.50%]
9            British Chinese - [1.67%]
10     Gypsy Irish Traveller - [0.10%]  , 'ethnicity_pct_ranking_table_shading': [['', '', ''], ['#D5F5E3', '', ''], ['#EAFAF1', '#EAFAF1', ''], ['#D5F5E3', '', ''], ['#D5F5E3', '#EAFAF1', ''], ['', '#EAFAF1', ''], ['#D5F5E3', '#EAFAF1', ''], ['', '#EAFAF1', ''], ['#EAFAF1', '#EAFAF1', ''], ['', '', '']], 'ethnicity_pct_comparison_table':                                        Ethnicity Dundonald  Merton  London
Black African Caribbean  Black African Caribbean     1.52%  10.42%  12.24%
British Asian Other          British Asian Other     3.82%   7.95%   4.75%
British Bangladeshi          British Bangladeshi     0.47%   1.11%   2.55%
British Chinese                  British Chinese     1.27%   1.31%   1.67%
British Indian                    British Indian     3.59%   4.06%   6.31%
British Pakistani              British Pakistani     1.22%   3.67%   2.50%
Gypsy Irish Traveller      Gypsy Irish Traveller     0.02%   0.11%   0.10%
Mixed Ethnic                        Mixed Ethnic     4.80%   4.67%   4.88%
Other                                      Other     1.40%   1.90%   3.39%
White                                      White    81.89%  64.79%  61.61%, 'ethnicity_pct_comparison_table_shading': [['', '#D5F5E3', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '', '', '#EAFAF1'], ['', '#82E0AA', '', '#EAFAF1']], 'ethnicity_narrative_02': 'The table {} shows the percentage levels of ethnicity in Dundonald, Merton and London in 2011. The order of ethnicity is alphabetical. Value shading indicates a difference from the city level from 5 to 20 percent in 5 percent intervals. The shade darkens with an increase in difference. Indication of the direction of the difference is intentionally not made.', 'template_processor_file_name': './reports/processors/sd_test_generation_03_ethnicity.json', 'report_option': 1}
2022-08-28 15:20:09,564 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,565 [DEBUG] managers.sd_report_manager_new: >>>>>>>>>>>>>>>>>>>>>>>>>>>
2022-08-28 15:20:09,589 [DEBUG] __main__: Finished